<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLLNkFaT\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLLNkFaT/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLLNkFaT.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLLNkFaT\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLLNkFaT\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'LLNkFaT',
    'container.build_id' => '62858dcc',
    'container.build_time' => 1586427804,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLLNkFaT');
